language: en-US
reviews:
  poem: false
  auto_review:
    base_branches:
      - develop
  pre_merge_checks:
    custom_checks:
      - mode: 'warning'
        name: Commit check
        instructions: >
          Trong quá trình làm việc, có thể commit/amend commit ở local nhưng
          không nên push code lên github khi chưa hoàn thành feature, bugfix.
          Làm như vậy để giảm chi phí circleCI của cty cũng như tránh phải
          force-push nhiều lần không cần thiết.


          Tham khảo tips và best practices trong bài viết dưới đây:

          https://gist.github.com/luismts/495d982e8c5b1a0ced4a57cf3d93cf60


          Một vài điểm cần đặc biệt lưu ý:


          **1. Cần bắt đầu commit message với động từ**

          Ví dụ:

          `Implement <something>`

          `Fix bug <something>`

          `Add <something>`

          `Refactor <something>`

          ...


          Cần bỏ thói quen viết commit message dạng

          `refs #12345 ...`


          **2. Cần add link redmine vào description của commit nếu có thể.**

          Ví dụ, dev A tạo nhánh `feature/12345` để đối ứng 4 màn hình staff
          search, staff edit, staff add, staff view thì cần add link redmine vào
          từng commit như sau


          ![Image](https://user-images.githubusercontent.com/39513619/196329597-fccd9c37-f8d9-4353-97de-470dafd8e1d6.png)


          **3. Không commit liên tục nhiều message có cùng nội dung**

          Như hình dưới đây là NG


          ![Image](https://user-images.githubusercontent.com/39513619/196330047-3ad1ae41-403f-49c1-b52f-94c099990fd6.png)


          Trường hợp trên cần rebase trước khi tạo pull request. (khi ở trên
          nhánh feature, có thể force push, amend commit tuỳ ý)


          **4. Thông nhất sử dụng tiếng anh cho commit message, không được copy
          tiêu đề tiếng nhật của ticket redmine ghi vào commit message**

          Như hình dưới đây là NG


          ![Image](https://user-images.githubusercontent.com/39513619/196330973-f5bdb989-7d57-46ff-b846-afa6a06ee950.png)


          Đối với tên màn hình/tên api, sử dụng tên tiếng anh là tên file tài
          liệu thiết kế.

          Đối với tên field, sử dụng tên logic được ghi trong tài liệu thiết kế
          api hoặc tài liệu thiết kế db.


          **5. Đối với các commit fix bug**

          5.1 Đối với các bug level1, có thể commit với message đơn giản như
          sau:

          `Fix bug screen staff add S102_1`

          Trường hợp bug do dev tự phát hiện, không có ticket do tester tạo,
          không cần add link redmine vào description

          Trường hợp bug có ticket do tester tạo, có thể gom nhiều bug vào cùng
          1 commit như sau


          ![Image](https://user-images.githubusercontent.com/39513619/196332149-3e51d567-d677-4ee4-b8eb-690aa0e8cf2a.png)


          5.2 Nếu không phải bug level 1, cần commit với message chi tiết hơn
          như sau


          ![Image](https://user-images.githubusercontent.com/39513619/196333284-2a434183-3bfc-4728-8a9e-a96162dd30b4.png)


          **6. Đối với commit spec change, cần ghi rõ nội dung thay đổi vào
          commit message**

          Như hình dưới đây là NG


          ![Image](https://user-images.githubusercontent.com/39513619/196335288-15cb5983-8043-472f-a328-59a14c9d23f0.png)


          Cần commit với nội dung như sau

          Pattern A

          ![Image](https://user-images.githubusercontent.com/39513619/196335324-111bda2a-d999-442a-a1ef-58d5bf574ae1.png)


          hoặc

          Pattern B

          ![Image](https://user-images.githubusercontent.com/39513619/196335524-8397ee94-2d5e-4509-b83d-b2b4a35d2790.png)


          (Tuỳ vào độ dài của commit message mà phán đoán và commit theo pattern
          A hoặc pattern B)
knowledge_base:
  code_guidelines:
    filePatterns:
      - '**/coding-rules/*.md'
